// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKK82QWx6XwGdZTjQoD08INtKtjD70P24',
    appId: '1:1054679533404:web:98263c666d97b98312a399',
    messagingSenderId: '1054679533404',
    projectId: 'nyam-nyam-77a54',
    authDomain: 'nyam-nyam-77a54.firebaseapp.com',
    databaseURL: 'https://nyam-nyam-77a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nyam-nyam-77a54.firebasestorage.app',
    measurementId: 'G-JXZ3P2LQED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP6slcoDir-40ELQ5BIdNVjA9ZcFBKEbM',
    appId: '1:1054679533404:android:9ca71df0e6e2cdb312a399',
    messagingSenderId: '1054679533404',
    projectId: 'nyam-nyam-77a54',
    databaseURL: 'https://nyam-nyam-77a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nyam-nyam-77a54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSNYs3qcawqZGo02YokGs3EjomQoAsAs',
    appId: '1:1054679533404:ios:f83e473ae9563d8512a399',
    messagingSenderId: '1054679533404',
    projectId: 'nyam-nyam-77a54',
    databaseURL: 'https://nyam-nyam-77a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nyam-nyam-77a54.firebasestorage.app',
    iosBundleId: 'my.edu.unikl.nyamnyam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSNYs3qcawqZGo02YokGs3EjomQoAsAs',
    appId: '1:1054679533404:ios:53fc16d5e08f8a2c12a399',
    messagingSenderId: '1054679533404',
    projectId: 'nyam-nyam-77a54',
    databaseURL: 'https://nyam-nyam-77a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nyam-nyam-77a54.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
